In [1]:
from fixture.factory.dataset.ohlcv import factory_ohlcv_cycle

df = factory_ohlcv_cycle()
df

shape: (100, 6)
┌─────────────────────┬────────┬────────┬────────┬────────┬────────┐
│ Date                ┆ Open   ┆ High   ┆ Low    ┆ Close  ┆ Volume │
│ ---                 ┆ ---    ┆ ---    ┆ ---    ┆ ---    ┆ ---    │
│ datetime[μs]        ┆ f64    ┆ f64    ┆ f64    ┆ f64    ┆ i64    │
╞═════════════════════╪════════╪════════╪════════╪════════╪════════╡
│ 2000-01-01 00:00:00 ┆ 101.0  ┆ 101.27 ┆ 99.95  ┆ 100.02 ┆ 30881  │
│ 2000-01-02 00:00:00 ┆ 100.02 ┆ 100.02 ┆ 99.59  ┆ 99.79  ┆ 29298  │
│ 2000-01-03 00:00:00 ┆ 99.79  ┆ 101.06 ┆ 99.73  ┆ 101.02 ┆ 39248  │
│ 2000-01-04 00:00:00 ┆ 100.01 ┆ 100.34 ┆ 99.61  ┆ 99.88  ┆ 45314  │
│ 2000-01-05 00:00:00 ┆ 99.88  ┆ 100.35 ┆ 99.77  ┆ 100.19 ┆ 21266  │
│ …                   ┆ …      ┆ …      ┆ …      ┆ …      ┆ …      │
│ 2000-04-05 00:00:00 ┆ 108.55 ┆ 108.79 ┆ 107.76 ┆ 107.91 ┆ 35185  │
│ 2000-04-06 00:00:00 ┆ 107.91 ┆ 108.12 ┆ 107.35 ┆ 107.66 ┆ 23154  │
│ 2000-04-07 00:00:00 ┆ 107.66 ┆ 109.3  ┆ 107.51 ┆ 109.12 ┆ 11174  │
│ 2000-04-08 00:00:00 ┆ 108.03 ┆ 109.41 ┆ 107.7  ┆ 109.24 ┆ 37001  │
│ 2000-04-09 00:00:00 ┆ 109.24 ┆ 110.09 ┆ 109.1  ┆ 109.85 ┆ 10512  │
└─────────────────────┴────────┴────────┴────────┴────────┴────────┘

In [2]:
import plotly.express as px

fig = px.line(df, x="Date", y="Close")
fig.show()

In [3]:
import pandas_ta as ta
import polars as pl

# Date列をインデックスに設定
pandas_df = df.to_pandas().set_index('Date')
print(pandas_df)

# カスタム戦略を作成
my_strategy = ta.Strategy(
    name="base",
    ta=[
        # trend
        {"kind": "sma", "length": 5},
        {"kind": "sma", "length": 25},
        {"kind": "sma", "length": 75},
        # momentum
        {"kind": "rsi"},
        {"kind": "roc"},
        # volatility
        {"kind": "atr"},
        {"kind": "bbands"},
        # volume
        {"kind": "obv"},
        {"kind": "vwap"},
    ]
)

# 戦略を適用
pandas_df.ta.strategy(my_strategy)
# print(pandas_df[75:])

ta_pldf = pl.from_pandas(pandas_df[75:].reset_index())
ta_pldf

              Open    High     Low   Close  Volume
Date
2000-01-01  101.00  101.27   99.95  100.02   30881
2000-01-02  100.02  100.02   99.59   99.79   29298
2000-01-03   99.79  101.06   99.73  101.02   39248
2000-01-04  100.01  100.34   99.61   99.88   45314
2000-01-05   99.88  100.35   99.77  100.19   21266
...            ...     ...     ...     ...     ...
2000-04-05  108.55  108.79  107.76  107.91   35185
2000-04-06  107.91  108.12  107.35  107.66   23154
2000-04-07  107.66  109.30  107.51  109.12   11174
2000-04-08  108.03  109.41  107.70  109.24   37001
2000-04-09  109.24  110.09  109.10  109.85   10512

[100 rows x 5 columns]

shape: (25, 19)
┌──────────────┬────────┬────────┬────────┬───┬───────────┬───────────┬───────────┬────────────┐
│ Date         ┆ Open   ┆ High   ┆ Low    ┆ … ┆ BBB_5_2.0 ┆ BBP_5_2.0 ┆ OBV       ┆ VWAP_D     │
│ ---          ┆ ---    ┆ ---    ┆ ---    ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---        │
│ datetime[μs] ┆ f64    ┆ f64    ┆ f64    ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64        │
╞══════════════╪════════╪════════╪════════╪═══╪═══════════╪═══════════╪═══════════╪════════════╡
│ 2000-03-16   ┆ 98.64  ┆ 98.84  ┆ 97.5   ┆ … ┆ 3.841404  ┆ 0.780176  ┆ -183915.0 ┆ 98.003333  │
│ 00:00:00     ┆        ┆        ┆        ┆   ┆           ┆           ┆           ┆            │
│ 2000-03-17   ┆ 97.67  ┆ 98.81  ┆ 97.35  ┆ … ┆ 4.1896    ┆ 0.82799   ┆ -153936.0 ┆ 98.24      │
│ 00:00:00     ┆        ┆        ┆        ┆   ┆           ┆           ┆           ┆            │
│ 2000-03-18   ┆ 98.56  ┆ 99.9   ┆ 98.33  ┆ … ┆ 4.096378  ┆ 0.897932  ┆ -139613.0 ┆ 99.286667  │
│ 00:00:00     ┆        ┆        ┆        ┆   ┆           ┆           ┆           ┆            │
│ 2000-03-19   ┆ 98.63  ┆ 99.72  ┆ 98.51  ┆ … ┆ 3.362363  ┆ 0.743764  ┆ -156484.0 ┆ 99.206667  │
│ 00:00:00     ┆        ┆        ┆        ┆   ┆           ┆           ┆           ┆            │
│ 2000-03-20   ┆ 99.39  ┆ 99.96  ┆ 99.11  ┆ … ┆ 3.256093  ┆ 0.759906  ┆ -139308.0 ┆ 99.643333  │
│ 00:00:00     ┆        ┆        ┆        ┆   ┆           ┆           ┆           ┆            │
│ …            ┆ …      ┆ …      ┆ …      ┆ … ┆ …         ┆ …         ┆ …         ┆ …          │
│ 2000-04-05   ┆ 108.55 ┆ 108.79 ┆ 107.76 ┆ … ┆ 2.796237  ┆ 0.856807  ┆ 239204.0  ┆ 108.153333 │
│ 00:00:00     ┆        ┆        ┆        ┆   ┆           ┆           ┆           ┆            │
│ 2000-04-06   ┆ 107.91 ┆ 108.12 ┆ 107.35 ┆ … ┆ 2.246081  ┆ 0.688543  ┆ 216050.0  ┆ 107.71     │
│ 00:00:00     ┆        ┆        ┆        ┆   ┆           ┆           ┆           ┆            │
│ 2000-04-07   ┆ 107.66 ┆ 109.3  ┆ 107.51 ┆ … ┆ 3.214732  ┆ 0.904869  ┆ 227224.0  ┆ 108.643333 │
│ 00:00:00     ┆        ┆        ┆        ┆   ┆           ┆           ┆           ┆            │
│ 2000-04-08   ┆ 108.03 ┆ 109.41 ┆ 107.7  ┆ … ┆ 2.758687  ┆ 0.820706  ┆ 264225.0  ┆ 108.783333 │
│ 00:00:00     ┆        ┆        ┆        ┆   ┆           ┆           ┆           ┆            │
│ 2000-04-09   ┆ 109.24 ┆ 110.09 ┆ 109.1  ┆ … ┆ 3.068625  ┆ 0.827809  ┆ 274737.0  ┆ 109.68     │
│ 00:00:00     ┆        ┆        ┆        ┆   ┆           ┆           ┆           ┆            │
└──────────────┴────────┴────────┴────────┴───┴───────────┴───────────┴───────────┴────────────┘