In [1]:
from fixture.factory.dataset.ohlcv import factory_ohlcv_cycle

df = factory_ohlcv_cycle()
df

shape: (100, 6)
┌─────────────────────┬────────┬────────┬────────┬────────┬────────┐
│ Date                ┆ Open   ┆ High   ┆ Low    ┆ Close  ┆ Volume │
│ ---                 ┆ ---    ┆ ---    ┆ ---    ┆ ---    ┆ ---    │
│ datetime[μs]        ┆ f64    ┆ f64    ┆ f64    ┆ f64    ┆ i64    │
╞═════════════════════╪════════╪════════╪════════╪════════╪════════╡
│ 2000-01-01 00:00:00 ┆ 101.0  ┆ 101.19 ┆ 99.72  ┆ 99.96  ┆ 22856  │
│ 2000-01-02 00:00:00 ┆ 99.96  ┆ 100.31 ┆ 99.71  ┆ 100.08 ┆ 10231  │
│ 2000-01-03 00:00:00 ┆ 100.08 ┆ 100.32 ┆ 99.64  ┆ 99.87  ┆ 22167  │
│ 2000-01-04 00:00:00 ┆ 98.87  ┆ 100.01 ┆ 98.7   ┆ 99.81  ┆ 39679  │
│ 2000-01-05 00:00:00 ┆ 99.81  ┆ 101.22 ┆ 99.44  ┆ 101.16 ┆ 32144  │
│ …                   ┆ …      ┆ …      ┆ …      ┆ …      ┆ …      │
│ 2000-04-05 00:00:00 ┆ 107.43 ┆ 107.66 ┆ 107.11 ┆ 107.13 ┆ 34238  │
│ 2000-04-06 00:00:00 ┆ 107.13 ┆ 108.3  ┆ 106.94 ┆ 108.17 ┆ 14759  │
│ 2000-04-07 00:00:00 ┆ 108.17 ┆ 109.89 ┆ 108.01 ┆ 109.56 ┆ 14163  │
│ 2000-04-08 00:00:00 ┆ 108.46 ┆ 110.69 ┆ 108.32 ┆ 110.48 ┆ 47413  │
│ 2000-04-09 00:00:00 ┆ 110.48 ┆ 110.77 ┆ 109.61 ┆ 109.77 ┆ 20940  │
└─────────────────────┴────────┴────────┴────────┴────────┴────────┘

In [2]:
import plotly.express as px

fig = px.line(df, x="Date", y="Close")
fig.show()

In [3]:
import pandas_ta as ta
from numpy import nan as npNaN

# Date列をインデックスに設定
pandas_df = df.to_pandas().set_index('Date')
print(pandas_df)

# カスタム戦略を作成
my_strategy = ta.Strategy(
    name="基本指標",
    ta=[
        # trend
        {"kind": "sma", "length": 5},
        {"kind": "sma", "length": 25},
        {"kind": "sma", "length": 75},
        # momentum
        {"kind": "rsi"},
        {"kind": "roc"},
        # volatility
        {"kind": "atr"},
        {"kind": "bbands"},
        # volume
        {"kind": "obv"},
        {"kind": "vwap"},
    ]
)

# 戦略を適用
pandas_df.ta.strategy(my_strategy)
pandas_df[75:]

              Open    High     Low   Close  Volume
Date
2000-01-01  101.00  101.19   99.72   99.96   22856
2000-01-02   99.96  100.31   99.71  100.08   10231
2000-01-03  100.08  100.32   99.64   99.87   22167
2000-01-04   98.87  100.01   98.70   99.81   39679
2000-01-05   99.81  101.22   99.44  101.16   32144
...            ...     ...     ...     ...     ...
2000-04-05  107.43  107.66  107.11  107.13   34238
2000-04-06  107.13  108.30  106.94  108.17   14759
2000-04-07  108.17  109.89  108.01  109.56   14163
2000-04-08  108.46  110.69  108.32  110.48   47413
2000-04-09  110.48  110.77  109.61  109.77   20940

[100 rows x 5 columns]

,Open,High,Low,Close,Volume,SMA_5,SMA_25,SMA_75,RSI_14,ROC_10,ATRr_14,BBL_5_2.0,BBM_5_2.0,BBU_5_2.0,BBB_5_2.0,BBP_5_2.0,OBV,VWAP_D
Date,,,,,,,,,,,,,,,,,,
2000-03-16,97.75,98.40,97.58,98.20,44102,96.714,97.0960,100.731867,54.208406,1.039202,1.304101,95.123649,96.714,98.304351,3.288771,0.967192,-20054.0,98.060000
2000-03-17,98.20,98.52,97.88,98.25,18518,97.180,97.0636,100.707467,54.469728,2.868810,1.256494,95.435385,97.180,98.924615,3.590481,0.806658,-1536.0,98.216667
2000-03-18,98.25,99.84,98.11,99.44,44429,97.826,97.0420,100.701733,60.279592,5.260929,1.290429,95.656259,97.826,99.995741,4.435919,0.871934,42893.0,99.130000
2000-03-19,98.44,100.13,98.38,99.80,32236,98.494,97.0860,100.701600,61.864960,4.864978,1.323357,96.361524,98.494,100.626476,4.330165,0.806217,75129.0,99.436667
2000-03-20,99.80,100.28,99.65,99.96,47198,99.130,97.1164,100.685600,62.579826,5.443038,1.273689,97.613900,99.130,100.646100,3.058812,0.773729,122327.0,99.963333
2000-03-21,100.96,101.24,100.11,100.45,37385,99.580,97.1776,100.679733,64.758609,5.881733,1.274141,98.099946,99.580,101.060054,2.972593,0.793908,159712.0,100.600000
2000-03-22,100.45,100.68,100.20,100.36,20698,100.002,97.2580,100.669600,64.021276,4.628857,1.217276,99.260499,100.002,100.743501,1.482973,0.741402,139014.0,100.413333
2000-03-23,100.36,101.31,100.08,101.20,17733,100.354,97.3960,100.680267,67.715946,5.186571,1.218187,99.379477,100.354,101.328523,1.942172,0.934058,156747.0,100.863333
2000-03-24,100.19,102.36,99.94,102.13,38350,100.820,97.5596,100.692400,71.237576,5.878084,1.304214,99.284135,100.820,102.355865,3.046746,0.926470,195097.0,101.476667
2000-03-25,102.13,102.72,101.98,102.41,14425,101.310,97.7740,100.681733,72.220107,5.817318,1.263833,99.627954,101.310,102.992046,3.320593,0.826983,209522.0,102.370000
2000-03-26,103.43,103.98,103.20,103.56,12217,101.932,98.0136,100.697600,75.866513,5.458248,1.285743,99.754831,101.932,104.109169,4.271806,0.873880,221739.0,103.580000
2000-03-27,103.56,103.86,103.30,103.57,26658,102.574,98.2504,100.709600,75.896142,5.414758,1.233815,100.768205,102.574,104.379795,3.520961,0.775779,248397.0,103.576667
2000-03-28,103.57,103.97,103.37,103.71,47616,103.076,98.5080,100.728933,76.334190,4.294047,1.188471,101.743718,103.076,104.408282,2.585048,0.737938,296013.0,103.683333
2000-03-29,102.67,103.92,102.41,103.69,26785,103.388,98.8308,100.753200,76.121362,3.897796,1.211471,102.402473,103.388,104.373527,1.906464,0.653217,269228.0,103.340000
2000-03-30,103.69,105.36,103.45,105.12,27937,103.930,99.1692,100.790533,80.341692,5.162065,1.261434,102.733806,103.930,105.126194,2.301922,0.997411,297165.0,104.643333
2000-03-31,106.18,106.36,105.49,105.55,14553,104.328,99.5036,100.827200,81.405905,5.077153,1.259901,102.658490,104.328,105.997510,3.200502,0.865976,311718.0,105.800000
2000-04-01,105.55,105.72,105.06,105.31,18685,104.676,99.8956,100.868533,78.840479,4.932244,1.217001,103.059010,104.676,106.292990,3.089514,0.696043,293033.0,105.363333
2000-04-02,105.31,107.00,105.03,106.82,11750,105.298,100.3896,100.916800,82.563626,5.553360,1.270845,103.298504,105.298,107.297496,3.797785,0.880596,304783.0,106.283333
2000-04-03,105.75,107.46,105.72,107.19,34061,105.998,100.8704,100.965867,83.337302,4.954470,1.304390,104.314794,105.998,107.681206,3.175921,0.854086,338844.0,106.790000
2000-04-04,107.19,107.37,106.18,106.36,20922,106.246,101.3328,100.995333,75.269034,3.857045,1.296212,104.805411,106.246,107.686589,2.711799,0.539567,317922.0,106.636667
2000-04-05,107.43,107.66,107.11,107.13,34238,106.562,101.8232,101.040133,77.450164,3.447277,1.296483,105.178705,106.562,107.945295,2.596225,0.705307,352160.0,107.300000
2000-04-06,107.13,108.30,106.94,108.17,14759,107.134,102.3132,101.098933,80.014018,4.441441,1.301023,105.942658,107.134,108.325342,2.224022,0.934804,366919.0,107.803333
2000-04-07,108.17,109.89,108.01,109.56,14163,107.682,102.8472,101.165333,82.824748,5.640729,1.342410,105.480277,107.682,109.883723,4.089305,0.926484,381082.0,109.153333
2000-04-08,108.46,110.69,108.32,110.48,47413,108.340,103.4080,101.265467,84.389575,6.548365,1.415861,105.309304,108.340,111.370696,5.594787,0.853054,428495.0,109.830000
2000-04-09,110.48,110.77,109.61,109.77,20940,109.022,103.9276,101.337067,78.449290,4.423516,1.397573,106.608657,109.022,111.435343,4.427259,0.654972,407555.0,110.050000