In [1]:
from fixture.factory.dataset.ohlcv import factory_ohlcv_cycle

df = factory_ohlcv_cycle()
df

shape: (100, 6)
┌─────────────────────┬────────┬────────┬────────┬────────┬────────┐
│ Date                ┆ Open   ┆ High   ┆ Low    ┆ Close  ┆ Volume │
│ ---                 ┆ ---    ┆ ---    ┆ ---    ┆ ---    ┆ ---    │
│ datetime[μs]        ┆ f64    ┆ f64    ┆ f64    ┆ f64    ┆ i64    │
╞═════════════════════╪════════╪════════╪════════╪════════╪════════╡
│ 2000-01-01 00:00:00 ┆ 101.0  ┆ 101.31 ┆ 99.12  ┆ 99.45  ┆ 23163  │
│ 2000-01-02 00:00:00 ┆ 99.45  ┆ 100.29 ┆ 99.34  ┆ 100.04 ┆ 17779  │
│ 2000-01-03 00:00:00 ┆ 100.04 ┆ 100.28 ┆ 100.0  ┆ 100.05 ┆ 10639  │
│ 2000-01-04 00:00:00 ┆ 99.05  ┆ 100.9  ┆ 98.79  ┆ 100.81 ┆ 49013  │
│ 2000-01-05 00:00:00 ┆ 100.81 ┆ 101.86 ┆ 100.45 ┆ 101.46 ┆ 31505  │
│ …                   ┆ …      ┆ …      ┆ …      ┆ …      ┆ …      │
│ 2000-04-05 00:00:00 ┆ 108.66 ┆ 108.8  ┆ 107.65 ┆ 107.69 ┆ 11474  │
│ 2000-04-06 00:00:00 ┆ 107.69 ┆ 108.85 ┆ 107.48 ┆ 108.69 ┆ 35425  │
│ 2000-04-07 00:00:00 ┆ 108.69 ┆ 109.67 ┆ 108.65 ┆ 109.35 ┆ 25258  │
│ 2000-04-08 00:00:00 ┆ 108.26 ┆ 110.35 ┆ 107.96 ┆ 110.34 ┆ 35114  │
│ 2000-04-09 00:00:00 ┆ 110.34 ┆ 110.61 ┆ 109.76 ┆ 110.21 ┆ 19283  │
└─────────────────────┴────────┴────────┴────────┴────────┴────────┘

In [2]:
from feature.closes.derive import derive_closes, derive_closes_n4


closes = derive_closes(df)
closes

shape: (95, 6)
┌─────────────────────┬────────────┬────────────┬────────────┬────────────┬────────────┐
│ Date                ┆ now        ┆ lag_1      ┆ lag_2      ┆ lag_3      ┆ lag_4      │
│ ---                 ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│ datetime[μs]        ┆ f64        ┆ f64        ┆ f64        ┆ f64        ┆ f64        │
╞═════════════════════╪════════════╪════════════╪════════════╪════════════╪════════════╡
│ 2000-01-06 00:00:00 ┆ -56.338177 ┆ 64.270751  ┆ 75.67496   ┆ 0.99955    ┆ 59.151007  │
│ 2000-01-07 00:00:00 ┆ 40.555968  ┆ -56.338177 ┆ 64.270751  ┆ 75.67496   ┆ 0.99955    │
│ 2000-01-08 00:00:00 ┆ -41.547196 ┆ 40.555968  ┆ -56.338177 ┆ 64.270751  ┆ 75.67496   │
│ 2000-01-09 00:00:00 ┆ 60.285798  ┆ -41.547196 ┆ 40.555968  ┆ -56.338177 ┆ 64.270751  │
│ 2000-01-10 00:00:00 ┆ 76.561034  ┆ 60.285798  ┆ -41.547196 ┆ 40.555968  ┆ -56.338177 │
│ …                   ┆ …          ┆ …          ┆ …          ┆ …          ┆ …          │
│ 2000-04-05 00:00:00 ┆ 9.290227   ┆ 48.448804  ┆ -27.979873 ┆ 87.933214  ┆ 125.752142 │
│ 2000-04-06 00:00:00 ┆ 92.430642  ┆ 9.290227   ┆ 48.448804  ┆ -27.979873 ┆ 87.933214  │
│ 2000-04-07 00:00:00 ┆ 60.539535  ┆ 92.430642  ┆ 9.290227   ┆ 48.448804  ┆ -27.979873 │
│ 2000-04-08 00:00:00 ┆ 90.127607  ┆ 60.539535  ┆ 92.430642  ┆ 9.290227   ┆ 48.448804  │
│ 2000-04-09 00:00:00 ┆ -11.788711 ┆ 90.127607  ┆ 60.539535  ┆ 92.430642  ┆ 9.290227   │
└─────────────────────┴────────────┴────────────┴────────────┴────────────┴────────────┘

In [3]:
closes_n4 = derive_closes_n4(df)
closes_n4

shape: (95, 6)
┌─────────────────────┬────────────┬────────────┬────────────┬────────────┬────────────┐
│ Date                ┆ now        ┆ lag_1      ┆ lag_2      ┆ lag_3      ┆ lag_4      │
│ ---                 ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│ datetime[μs]        ┆ f64        ┆ f64        ┆ f64        ┆ f64        ┆ f64        │
╞═════════════════════╪════════════╪════════════╪════════════╪════════════╪════════════╡
│ 2000-01-06 00:00:00 ┆ -56.338177 ┆ 64.270751  ┆ 75.67496   ┆ 0.99955    ┆ 59.151007  │
│ 2000-01-07 00:00:00 ┆ 40.555968  ┆ -56.338177 ┆ 64.270751  ┆ 75.67496   ┆ 0.99955    │
│ 2000-01-08 00:00:00 ┆ -41.547196 ┆ 40.555968  ┆ -56.338177 ┆ 64.270751  ┆ 75.67496   │
│ 2000-01-09 00:00:00 ┆ 60.285798  ┆ -41.547196 ┆ 40.555968  ┆ -56.338177 ┆ 64.270751  │
│ 2000-01-10 00:00:00 ┆ 76.561034  ┆ 60.285798  ┆ -41.547196 ┆ 40.555968  ┆ -56.338177 │
│ …                   ┆ …          ┆ …          ┆ …          ┆ …          ┆ …          │
│ 2000-04-05 00:00:00 ┆ 9.290227   ┆ 48.448804  ┆ -27.979873 ┆ 87.933214  ┆ 125.752142 │
│ 2000-04-06 00:00:00 ┆ 92.430642  ┆ 9.290227   ┆ 48.448804  ┆ -27.979873 ┆ 87.933214  │
│ 2000-04-07 00:00:00 ┆ 60.539535  ┆ 92.430642  ┆ 9.290227   ┆ 48.448804  ┆ -27.979873 │
│ 2000-04-08 00:00:00 ┆ 90.127607  ┆ 60.539535  ┆ 92.430642  ┆ 9.290227   ┆ 48.448804  │
│ 2000-04-09 00:00:00 ┆ -11.788711 ┆ 90.127607  ┆ 60.539535  ┆ 92.430642  ┆ 9.290227   │
└─────────────────────┴────────────┴────────────┴────────────┴────────────┴────────────┘

In [4]:
closes.equals(closes_n4)

True