In [3]:
from fixture.domain.dataset.ohlcv import factory_ohlcv_cycle

ohlcv = factory_ohlcv_cycle()
ohlcv.df

shape: (100, 6)
┌─────────────────────┬────────┬────────┬────────┬────────┬────────┐
│ Date                ┆ Open   ┆ High   ┆ Low    ┆ Close  ┆ Volume │
│ ---                 ┆ ---    ┆ ---    ┆ ---    ┆ ---    ┆ ---    │
│ datetime[μs]        ┆ f64    ┆ f64    ┆ f64    ┆ f64    ┆ i64    │
╞═════════════════════╪════════╪════════╪════════╪════════╪════════╡
│ 2000-01-01 00:00:00 ┆ 101.0  ┆ 101.19 ┆ 100.07 ┆ 100.4  ┆ 29311  │
│ 2000-01-02 00:00:00 ┆ 100.4  ┆ 100.58 ┆ 100.36 ┆ 100.4  ┆ 25983  │
│ 2000-01-03 00:00:00 ┆ 100.4  ┆ 101.39 ┆ 100.07 ┆ 101.19 ┆ 26844  │
│ 2000-01-04 00:00:00 ┆ 100.18 ┆ 100.94 ┆ 99.96  ┆ 100.73 ┆ 14925  │
│ 2000-01-05 00:00:00 ┆ 100.73 ┆ 100.88 ┆ 99.97  ┆ 100.12 ┆ 14355  │
│ …                   ┆ …      ┆ …      ┆ …      ┆ …      ┆ …      │
│ 2000-04-05 00:00:00 ┆ 107.71 ┆ 107.85 ┆ 107.21 ┆ 107.47 ┆ 30858  │
│ 2000-04-06 00:00:00 ┆ 107.47 ┆ 108.18 ┆ 107.01 ┆ 108.09 ┆ 49541  │
│ 2000-04-07 00:00:00 ┆ 108.09 ┆ 108.4  ┆ 107.85 ┆ 108.18 ┆ 10774  │
│ 2000-04-08 00:00:00 ┆ 107.1  ┆ 109.29 ┆ 107.03 ┆ 109.25 ┆ 34486  │
│ 2000-04-09 00:00:00 ┆ 109.25 ┆ 110.56 ┆ 109.04 ┆ 110.47 ┆ 23589  │
└─────────────────────┴────────┴────────┴────────┴────────┴────────┘

In [4]:
import plotly.express as px

fig = px.line(ohlcv.df, x="Date", y="Close")
fig.show()

In [5]:
import pandas_ta as ta
import polars as pl

# Date列をインデックスに設定
pandas_df = ohlcv.df.to_pandas().set_index("Date")
print(pandas_df)

# カスタム戦略を作成
my_strategy = ta.Strategy(
    name="base",
    ta=[
        # trend
        {"kind": "sma", "length": 5},
        {"kind": "sma", "length": 25},
        {"kind": "sma", "length": 75},
        # momentum
        {"kind": "rsi"},
        {"kind": "roc"},
        # volatility
        {"kind": "atr"},
        {"kind": "bbands"},
        # volume
        {"kind": "obv"},
        {"kind": "vwap"},
    ],
)

# 戦略を適用
pandas_df.ta.strategy(my_strategy)
# print(pandas_df[75:])

ta_pldf = pl.from_pandas(pandas_df[75:].reset_index())
ta_pldf

              Open    High     Low   Close  Volume
Date
2000-01-01  101.00  101.19  100.07  100.40   29311
2000-01-02  100.40  100.58  100.36  100.40   25983
2000-01-03  100.40  101.39  100.07  101.19   26844
2000-01-04  100.18  100.94   99.96  100.73   14925
2000-01-05  100.73  100.88   99.97  100.12   14355
...            ...     ...     ...     ...     ...
2000-04-05  107.71  107.85  107.21  107.47   30858
2000-04-06  107.47  108.18  107.01  108.09   49541
2000-04-07  108.09  108.40  107.85  108.18   10774
2000-04-08  107.10  109.29  107.03  109.25   34486
2000-04-09  109.25  110.56  109.04  110.47   23589

[100 rows x 5 columns]

shape: (25, 19)
┌──────────────┬────────┬────────┬────────┬───┬───────────┬───────────┬───────────┬────────────┐
│ Date         ┆ Open   ┆ High   ┆ Low    ┆ … ┆ BBB_5_2.0 ┆ BBP_5_2.0 ┆ OBV       ┆ VWAP_D     │
│ ---          ┆ ---    ┆ ---    ┆ ---    ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---        │
│ datetime[μs] ┆ f64    ┆ f64    ┆ f64    ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64        │
╞══════════════╪════════╪════════╪════════╪═══╪═══════════╪═══════════╪═══════════╪════════════╡
│ 2000-03-16   ┆ 98.81  ┆ 99.08  ┆ 97.7   ┆ … ┆ 3.830519  ┆ 0.768223  ┆ -320747.0 ┆ 98.173333  │
│ 00:00:00     ┆        ┆        ┆        ┆   ┆           ┆           ┆           ┆            │
│ 2000-03-17   ┆ 97.74  ┆ 98.31  ┆ 97.68  ┆ … ┆ 3.586576  ┆ 0.747193  ┆ -304980.0 ┆ 98.026667  │
│ 00:00:00     ┆        ┆        ┆        ┆   ┆           ┆           ┆           ┆            │
│ 2000-03-18   ┆ 98.09  ┆ 98.83  ┆ 97.84  ┆ … ┆ 2.658547  ┆ 0.851437  ┆ -290944.0 ┆ 98.47      │
│ 00:00:00     ┆        ┆        ┆        ┆   ┆           ┆           ┆           ┆            │
│ 2000-03-19   ┆ 97.75  ┆ 99.25  ┆ 97.44  ┆ … ┆ 2.162567  ┆ 0.876328  ┆ -246008.0 ┆ 98.596667  │
│ 00:00:00     ┆        ┆        ┆        ┆   ┆           ┆           ┆           ┆            │
│ 2000-03-20   ┆ 99.1   ┆ 100.94 ┆ 99.01  ┆ … ┆ 4.338707  ┆ 0.947925  ┆ -196607.0 ┆ 100.256667 │
│ 00:00:00     ┆        ┆        ┆        ┆   ┆           ┆           ┆           ┆            │
│ …            ┆ …      ┆ …      ┆ …      ┆ … ┆ …         ┆ …         ┆ …         ┆ …          │
│ 2000-04-05   ┆ 107.71 ┆ 107.85 ┆ 107.21 ┆ … ┆ 2.386792  ┆ 0.85938   ┆ -90272.0  ┆ 107.51     │
│ 00:00:00     ┆        ┆        ┆        ┆   ┆           ┆           ┆           ┆            │
│ 2000-04-06   ┆ 107.47 ┆ 108.18 ┆ 107.01 ┆ … ┆ 2.2749    ┆ 0.915449  ┆ -40731.0  ┆ 107.76     │
│ 00:00:00     ┆        ┆        ┆        ┆   ┆           ┆           ┆           ┆            │
│ 2000-04-07   ┆ 108.09 ┆ 108.4  ┆ 107.85 ┆ … ┆ 2.620464  ┆ 0.78574   ┆ -29957.0  ┆ 108.143333 │
│ 00:00:00     ┆        ┆        ┆        ┆   ┆           ┆           ┆           ┆            │
│ 2000-04-08   ┆ 107.1  ┆ 109.29 ┆ 107.03 ┆ … ┆ 3.190867  ┆ 0.884462  ┆ 4529.0    ┆ 108.523333 │
│ 00:00:00     ┆        ┆        ┆        ┆   ┆           ┆           ┆           ┆            │
│ 2000-04-09   ┆ 109.25 ┆ 110.56 ┆ 109.04 ┆ … ┆ 3.891365  ┆ 0.92037   ┆ 28118.0   ┆ 110.023333 │
│ 00:00:00     ┆        ┆        ┆        ┆   ┆           ┆           ┆           ┆            │
└──────────────┴────────┴────────┴────────┴───┴───────────┴───────────┴───────────┴────────────┘