In [1]:
from fixture.domain.feature.lag import factory_lag_closes10

lag = factory_lag_closes10()
lag.df

,l0,l1,l2,l3,l4,l5,l6,l7,l8,l9,l10
Date,,,,,,,,,,,
2020-01-01 00:11:00,0.000500,-0.000300,-0.000500,0.000600,-0.000200,0.000100,-0.000200,0.000400,0.000400,0.000100,-0.000200
2020-01-01 00:12:00,-0.000500,0.000500,-0.000300,-0.000500,0.000600,-0.000200,0.000100,-0.000200,0.000400,0.000400,0.000100
2020-01-01 00:13:00,0.000000,-0.000500,0.000500,-0.000300,-0.000500,0.000600,-0.000200,0.000100,-0.000200,0.000400,0.000400
2020-01-01 00:14:00,0.000000,0.000000,-0.000500,0.000500,-0.000300,-0.000500,0.000600,-0.000200,0.000100,-0.000200,0.000400
2020-01-01 00:15:00,0.000300,0.000000,0.000000,-0.000500,0.000500,-0.000300,-0.000500,0.000600,-0.000200,0.000100,-0.000200
...,...,...,...,...,...,...,...,...,...,...,...
2020-01-01 16:35:00,0.000799,-0.000200,-0.000798,0.000100,0.000200,0.000299,-0.000399,-0.000399,0.000100,0.000798,-0.000299
2020-01-01 16:36:00,-0.000299,0.000799,-0.000200,-0.000798,0.000100,0.000200,0.000299,-0.000399,-0.000399,0.000100,0.000798
2020-01-01 16:37:00,0.000200,-0.000299,0.000799,-0.000200,-0.000798,0.000100,0.000200,0.000299,-0.000399,-0.000399,0.000100
2020-01-01 16:38:00,0.000299,0.000200,-0.000299,0.000799,-0.000200,-0.000798,0.000100,0.000200,0.000299,-0.000399,-0.000399
2020-01-01 16:39:00,-0.000798,0.000299,0.000200,-0.000299,0.000799,-0.000200,-0.000798,0.000100,0.000200,0.000299,-0.000399

In [2]:
# ohlcvがくっついている
lag.df_with_ohlcv

,Open,High,Low,Close,Volume,l0,l1,l2,l3,l4,l5,l6,l7,l8,l9,l10
Date,,,,,,,,,,,,,,,,
2020-01-01 00:11:00,100.07,100.07,99.98,100.05,2175,0.000500,-0.000300,-0.000500,0.000600,-0.000200,0.000100,-0.000200,0.000400,0.000400,0.000100,-0.000200
2020-01-01 00:12:00,100.02,100.06,99.92,100.00,1000,-0.000500,0.000500,-0.000300,-0.000500,0.000600,-0.000200,0.000100,-0.000200,0.000400,0.000400,0.000100
2020-01-01 00:13:00,100.05,100.10,99.92,100.00,12916,0.000000,-0.000500,0.000500,-0.000300,-0.000500,0.000600,-0.000200,0.000100,-0.000200,0.000400,0.000400
2020-01-01 00:14:00,99.96,100.07,99.93,100.00,11266,0.000000,0.000000,-0.000500,0.000500,-0.000300,-0.000500,0.000600,-0.000200,0.000100,-0.000200,0.000400
2020-01-01 00:15:00,100.04,100.10,99.94,100.03,4549,0.000300,0.000000,0.000000,-0.000500,0.000500,-0.000300,-0.000500,0.000600,-0.000200,0.000100,-0.000200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-01-01 16:35:00,100.15,100.21,100.13,100.21,7814,0.000799,-0.000200,-0.000798,0.000100,0.000200,0.000299,-0.000399,-0.000399,0.000100,0.000798,-0.000299
2020-01-01 16:36:00,100.16,100.23,100.15,100.18,9013,-0.000299,0.000799,-0.000200,-0.000798,0.000100,0.000200,0.000299,-0.000399,-0.000399,0.000100,0.000798
2020-01-01 16:37:00,100.19,100.29,100.19,100.20,11840,0.000200,-0.000299,0.000799,-0.000200,-0.000798,0.000100,0.000200,0.000299,-0.000399,-0.000399,0.000100
2020-01-01 16:38:00,100.14,100.27,100.06,100.23,15348,0.000299,0.000200,-0.000299,0.000799,-0.000200,-0.000798,0.000100,0.000200,0.000299,-0.000399,-0.000399
2020-01-01 16:39:00,100.14,100.18,100.13,100.15,1000,-0.000798,0.000299,0.000200,-0.000299,0.000799,-0.000200,-0.000798,0.000100,0.000200,0.000299,-0.000399

In [3]:
# l0が消えてる
lag.df_feature_with_ohlcv

,Open,High,Low,Close,Volume,l1,l2,l3,l4,l5,l6,l7,l8,l9,l10
Date,,,,,,,,,,,,,,,
2020-01-01 00:11:00,100.07,100.07,99.98,100.05,2175,-0.000300,-0.000500,0.000600,-0.000200,0.000100,-0.000200,0.000400,0.000400,0.000100,-0.000200
2020-01-01 00:12:00,100.02,100.06,99.92,100.00,1000,0.000500,-0.000300,-0.000500,0.000600,-0.000200,0.000100,-0.000200,0.000400,0.000400,0.000100
2020-01-01 00:13:00,100.05,100.10,99.92,100.00,12916,-0.000500,0.000500,-0.000300,-0.000500,0.000600,-0.000200,0.000100,-0.000200,0.000400,0.000400
2020-01-01 00:14:00,99.96,100.07,99.93,100.00,11266,0.000000,-0.000500,0.000500,-0.000300,-0.000500,0.000600,-0.000200,0.000100,-0.000200,0.000400
2020-01-01 00:15:00,100.04,100.10,99.94,100.03,4549,0.000000,0.000000,-0.000500,0.000500,-0.000300,-0.000500,0.000600,-0.000200,0.000100,-0.000200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-01-01 16:35:00,100.15,100.21,100.13,100.21,7814,-0.000200,-0.000798,0.000100,0.000200,0.000299,-0.000399,-0.000399,0.000100,0.000798,-0.000299
2020-01-01 16:36:00,100.16,100.23,100.15,100.18,9013,0.000799,-0.000200,-0.000798,0.000100,0.000200,0.000299,-0.000399,-0.000399,0.000100,0.000798
2020-01-01 16:37:00,100.19,100.29,100.19,100.20,11840,-0.000299,0.000799,-0.000200,-0.000798,0.000100,0.000200,0.000299,-0.000399,-0.000399,0.000100
2020-01-01 16:38:00,100.14,100.27,100.06,100.23,15348,0.000200,-0.000299,0.000799,-0.000200,-0.000798,0.000100,0.000200,0.000299,-0.000399,-0.000399
2020-01-01 16:39:00,100.14,100.18,100.13,100.15,1000,0.000299,0.000200,-0.000299,0.000799,-0.000200,-0.000798,0.000100,0.000200,0.000299,-0.000399

In [4]:
from backtesting import Strategy


class LagStrategy(Strategy):
    def init(self):
        pass

    def next(self):
        pass

    def calc_model(model):
        pass

/Users/tau/Repository/sitagaki2/.venv/lib/python3.11/site-packages/backtesting/_plotting.py:55: UserWarning: Jupyter Notebook detected. Setting Bokeh output to notebook. This may not work in Jupyter clients without JavaScript support, such as old IDEs. Reset with `backtesting.set_bokeh_output(notebook=False)`.
  warnings.warn('Jupyter Notebook detected. '