In [2]:
from fixture.factory.dataset.ohlcv import factory_ohlcv_cycle

ohlcv = factory_ohlcv_cycle()
ohlcv.df

shape: (100, 6)
┌─────────────────────┬────────┬────────┬────────┬────────┬────────┐
│ Date                ┆ Open   ┆ High   ┆ Low    ┆ Close  ┆ Volume │
│ ---                 ┆ ---    ┆ ---    ┆ ---    ┆ ---    ┆ ---    │
│ datetime[μs]        ┆ f64    ┆ f64    ┆ f64    ┆ f64    ┆ i64    │
╞═════════════════════╪════════╪════════╪════════╪════════╪════════╡
│ 2000-01-01 00:00:00 ┆ 101.0  ┆ 101.3  ┆ 99.59  ┆ 99.8   ┆ 47076  │
│ 2000-01-02 00:00:00 ┆ 99.8   ┆ 100.07 ┆ 99.55  ┆ 99.8   ┆ 14994  │
│ 2000-01-03 00:00:00 ┆ 99.8   ┆ 101.18 ┆ 99.62  ┆ 101.05 ┆ 40103  │
│ 2000-01-04 00:00:00 ┆ 100.04 ┆ 101.02 ┆ 99.77  ┆ 100.89 ┆ 27479  │
│ 2000-01-05 00:00:00 ┆ 100.89 ┆ 100.96 ┆ 100.23 ┆ 100.51 ┆ 36588  │
│ …                   ┆ …      ┆ …      ┆ …      ┆ …      ┆ …      │
│ 2000-04-05 00:00:00 ┆ 108.53 ┆ 108.8  ┆ 107.01 ┆ 107.18 ┆ 12212  │
│ 2000-04-06 00:00:00 ┆ 107.18 ┆ 109.17 ┆ 106.83 ┆ 108.73 ┆ 35409  │
│ 2000-04-07 00:00:00 ┆ 108.73 ┆ 109.36 ┆ 108.6  ┆ 109.29 ┆ 11276  │
│ 2000-04-08 00:00:00 ┆ 108.2  ┆ 108.97 ┆ 107.97 ┆ 108.69 ┆ 43223  │
│ 2000-04-09 00:00:00 ┆ 108.69 ┆ 110.38 ┆ 108.61 ┆ 110.2  ┆ 19690  │
└─────────────────────┴────────┴────────┴────────┴────────┴────────┘

In [5]:
# pd dataframe形式に変換しておく
pddf = ohlcv.df.to_pandas().set_index("Date")
pddf

              Open    High     Low   Close  Volume
Date
2000-01-01  101.00  101.30   99.59   99.80   47076
2000-01-02   99.80  100.07   99.55   99.80   14994
2000-01-03   99.80  101.18   99.62  101.05   40103
2000-01-04  100.04  101.02   99.77  100.89   27479
2000-01-05  100.89  100.96  100.23  100.51   36588
...            ...     ...     ...     ...     ...
2000-04-05  108.53  108.80  107.01  107.18   12212
2000-04-06  107.18  109.17  106.83  108.73   35409
2000-04-07  108.73  109.36  108.60  109.29   11276
2000-04-08  108.20  108.97  107.97  108.69   43223
2000-04-09  108.69  110.38  108.61  110.20   19690

[100 rows x 5 columns]